### ISSUE TITLE
Feedback for Milestone 2

### ISSUE THREAD

**Issue by siddheshk** [UBC-MDS/DSCI_524_Group2_Python#43]
- [x] - The docstring for the functions isn't consistent. Some functions Parameters, others use Arguments, and there's one that uses @params. Make sure they're consistent. Also `fit_and_report` is missing an example in the docstring.
- [x] - Even for the functions in the test folder write a line or two in the docstring describing which function is being tested. 
- [x] - Add package dependencies in README
- [x] - Fix formatting of CONTRIBUTORS.md
