### ISSUE TITLE
Feedback for Milestone 3

### ISSUE THREAD

**Issue by siddheshk** [UBC-MDS/DSCI_524_Group2_Python#84]
- [x] - Some of the examples in readthedocs aren't formatted correctly. I think you might have used some incorrect docstring format in your code.
- [x] - Add links to the packages you mention in README for Python. (Xin)
- [x] - Add links to the packages you mention in README for R. (Andrea)
- [x] - Use the python markdown (in your python repo) when writing examples in your README. Just add a python after the three block quotes.
